id: cl-nagoya/ruri-v3-310m
source:
  type: huggingface
  name: cl-nagoya/ruri-v3-310m
  revision: 18b60fb8c2b9
method: dense
parameters:
  total: 314611968
  trainable: 314611968
  input_embedding: 78643200
  active: 235968768
embedding:
  truncate_dims: null
runtime:
  max_seq_length: 8192
  dtype: bf16
  trust_remote_code: false
  attn_implementation: flash_attention_2
  backend_library: sentence-transformers
  similarity_fn_name: cosine
target:
  datasets:
  - hakari-bench/NanoBEIR-ar
  - hakari-bench/NanoBEIR-de
  - hakari-bench/NanoBEIR-en
  - hakari-bench/NanoBEIR-es
  - hakari-bench/NanoBEIR-fr
  - hakari-bench/NanoBEIR-it
  - hakari-bench/NanoBEIR-ja
  - hakari-bench/NanoBEIR-ko
  - hakari-bench/NanoBEIR-no
  - hakari-bench/NanoBEIR-pt
  - hakari-bench/NanoBEIR-sr
  - hakari-bench/NanoBEIR-sv
  - hakari-bench/NanoBEIR-th
  - hakari-bench/NanoBEIR-vi
  - hakari-bench/NanoBIRCO
  - hakari-bench/NanoBRIGHT
  - hakari-bench/NanoBuiltBench
  - hakari-bench/NanoCMTEB
  - hakari-bench/NanoChemTEB
  - hakari-bench/NanoCoIR
  - hakari-bench/NanoCodeRAG
  - hakari-bench/NanoDAPFAM
  - hakari-bench/NanoFaMTEB-v2
  - hakari-bench/NanoIFIR
  - hakari-bench/NanoIndicQA
  - hakari-bench/NanoJMTEB-v2
  - hakari-bench/NanoLaw
  - hakari-bench/NanoLongEmbed
  - hakari-bench/NanoMIRACL
  - hakari-bench/NanoMLDR
  - hakari-bench/NanoMMTEB-v2
  - hakari-bench/NanoMTEB-Dutch
  - hakari-bench/NanoMTEB-French
  - hakari-bench/NanoMTEB-German
  - hakari-bench/NanoMTEB-Korean
  - hakari-bench/NanoMTEB-Misc
  - hakari-bench/NanoMTEB-Polish
  - hakari-bench/NanoMTEB-Scandinavian
  - hakari-bench/NanoMTEB-Spanish
  - hakari-bench/NanoMTEB-Thai
  - hakari-bench/NanoMTEB-v2
  - hakari-bench/NanoMedical
  - hakari-bench/NanoMuPLeR
  - hakari-bench/NanoR2MED
  - hakari-bench/NanoRARb
  - hakari-bench/NanoRTEB
  - hakari-bench/NanoRuMTEB
  - hakari-bench/NanoVNMTEB
