id: colbert-ir/colbertv2.0
source:
  type: huggingface
  name: colbert-ir/colbertv2.0
  revision: c1e84128e85ef755c096a95bdb06b47793b13acf
method: late-interaction
parameters:
  total: 109580544
  input_embedding: 0
  active: 109580544
embedding:
  truncate_dims: null
runtime:
  max_seq_length: 512
  dtype: bf16
  trust_remote_code: false
  attn_implementation: sdpa
  backend_library: pylate
late_interaction:
  architecture: colbert
  scoring: maxsim
  query_length: 48
  document_length: 512
target:
  datasets:
  - hakari-bench/NanoBEIR-en
