id: lightonai/GTE-ModernColBERT-v1
source:
  type: huggingface
  name: lightonai/GTE-ModernColBERT-v1
  revision: cbbe53366e564450558f5e639dd499171f127538
method: late-interaction
parameters:
  total: 149114112
  input_embedding: 38684160
  active: 110429952
embedding:
  truncate_dims: null
runtime:
  max_seq_length: 299
  dtype: fp32
  trust_remote_code: false
  attn_implementation: sdpa
  backend_library: pylate
late_interaction:
  architecture: colbert
  scoring: maxsim
  query_prefix: '[Q] '
  document_prefix: '[D] '
  query_length: 48
  document_length: 512
  do_query_expansion: false
  attend_to_expansion_tokens: false
target:
  datasets:
  - hakari-bench/NanoBEIR-en
