id: prithivida/Splade_PP_en_v2
source:
  type: huggingface
  name: prithivida/Splade_PP_en_v2
  revision: f0d4aa214dcb60c274052a52c0497535e3aec64c
method: sparse
parameters:
  total: 132985716
  input_embedding: 23440896
  active: 109544820
embedding:
  truncate_dims: null
runtime:
  max_seq_length: 512
  dtype: bf16
  trust_remote_code: false
  attn_implementation: sdpa
  backend_library: sentence-transformers
target:
  datasets:
  - hakari-bench/NanoBEIR-ar
  - hakari-bench/NanoBEIR-de
  - hakari-bench/NanoBEIR-en
  - hakari-bench/NanoBEIR-es
  - hakari-bench/NanoBEIR-fr
  - hakari-bench/NanoBEIR-it
  - hakari-bench/NanoBEIR-ja
  - hakari-bench/NanoBEIR-ko
  - hakari-bench/NanoBEIR-no
  - hakari-bench/NanoBEIR-pt
  - hakari-bench/NanoBEIR-sr
  - hakari-bench/NanoBEIR-sv
  - hakari-bench/NanoBEIR-th
  - hakari-bench/NanoBEIR-vi
  - hakari-bench/NanoBIRCO
  - hakari-bench/NanoBRIGHT
  - hakari-bench/NanoBuiltBench
  - hakari-bench/NanoCMTEB
  - hakari-bench/NanoChemTEB
  - hakari-bench/NanoCoIR
  - hakari-bench/NanoCodeRAG
  - hakari-bench/NanoDAPFAM
  - hakari-bench/NanoFaMTEB-v2
  - hakari-bench/NanoIFIR
  - hakari-bench/NanoIndicQA
  - hakari-bench/NanoJMTEB-v2
  - hakari-bench/NanoLaw
  - hakari-bench/NanoLongEmbed
  - hakari-bench/NanoMIRACL
  - hakari-bench/NanoMLDR
  - hakari-bench/NanoMMTEB-v2
  - hakari-bench/NanoMTEB-Dutch
  - hakari-bench/NanoMTEB-French
  - hakari-bench/NanoMTEB-German
  - hakari-bench/NanoMTEB-Korean
  - hakari-bench/NanoMTEB-Misc
  - hakari-bench/NanoMTEB-Polish
  - hakari-bench/NanoMTEB-Scandinavian
  - hakari-bench/NanoMTEB-Spanish
  - hakari-bench/NanoMTEB-Thai
  - hakari-bench/NanoMTEB-v2
  - hakari-bench/NanoMedical
  - hakari-bench/NanoMuPLeR
  - hakari-bench/NanoR2MED
  - hakari-bench/NanoRARb
  - hakari-bench/NanoRTEB
  - hakari-bench/NanoRuMTEB
  - hakari-bench/NanoVNMTEB
