benchmarks:
  - name: MNanoBEIR
    label: MNanoBEIR
    include_in_overall: true
    score_groups:
      - name: task_mean
        label: Task Mean
        group_by: task_name
      - name: lang_mean
        label: Lang Mean
        group_by: dataset_name
  - name: NanoRTEB
    label: NanoRTEB
    include_in_overall: true
  - name: NanoMTEB
    label: NanoMTEB
    include_in_overall: true
  - name: NanoMMTEB
    label: NanoMMTEB
    include_in_overall: true
  - name: NanoCodeSearchNet
    label: NanoCodeSearchNet
    include_in_overall: true
  - name: NanoMIRACL
    label: NanoMIRACL
    include_in_overall: true
  - name: NanoMLDR
    label: NanoMLDR
    include_in_overall: true
  - name: NanoLongEmbed
    label: NanoLongEmbed
    include_in_overall: true
  - name: NanoCoIR
    label: NanoCoIR
    include_in_overall: true
  - name: NanoJMTEB
    label: NanoJMTEB
    include_in_overall: false
