overalls:
  - name: Overall
    label: Overall
    benchmarks:
      - NanoMMTEB
      - NanoRTEB
      - MNanoBEIR
      - NanoBIRCO
      - NanoMLDR
      - NanoLongEmbed
      - NanoDAPFAM
      - NanoCoIR
      - NanoIFIR
      - NanoLaw
      - NanoMedical
      - NanoRARb
      - NanoBRIGHT
      - NanoCodeRAG
      - NanoChemTEB
      - NanoR2MED
      - NanoBuiltBench
      - NanoMTEB-Chinese
  - name: OverallGrouped
    label: Overall Grouped
    benchmarks:
      - name: MNanoBEIR
        group_by: task_name
      - name: NanoRTEB
        group_by: task_name
      - name: NanoMMTEB
        group_by: task_name
      - name: NanoBIRCO
        group_by: benchmark
      - name: NanoMLDR
        group_by: benchmark
      - name: NanoLongEmbed
        group_by: benchmark
      - name: NanoDAPFAM
        group_by: benchmark
      - name: NanoCoIR
        group_by: task_name
      - name: NanoIFIR
        group_by: benchmark
      - name: NanoLaw
        group_by: benchmark
      - name: NanoMedical
        group_by: benchmark
      - name: NanoRARb
        group_by: benchmark
      - name: NanoBRIGHT
        group_by: benchmark
      - name: NanoCodeRAG
        group_by: benchmark
      - name: NanoChemTEB
        group_by: benchmark
      - name: NanoR2MED
        group_by: benchmark
      - name: NanoBuiltBench
        group_by: benchmark
      - name: NanoMTEB-Chinese
        group_by: benchmark
      - name: NanoMTEB
        group_by: benchmark
      - name: NanoMTEB-Dutch
        group_by: benchmark
      - name: NanoMTEB-French
        group_by: benchmark
      - name: NanoMTEB-German
        group_by: benchmark
      - name: NanoMTEB-Japanese
        group_by: benchmark
      - name: NanoMTEB-Korean
        group_by: benchmark
      - name: NanoMTEB-Persian
        group_by: benchmark
      - name: NanoMTEB-Polish
        group_by: benchmark
      - name: NanoMTEB-Russian
        group_by: benchmark
      - name: NanoMTEB-Scandinavian
        group_by: benchmark
      - name: NanoMTEB-Spanish
        group_by: benchmark
      - name: NanoMTEB-Thai
        group_by: benchmark
      - name: NanoMTEB-Vietnamese
        group_by: benchmark
      - name: NanoMTEB-Xlingual
        group_by: benchmark
      - name: NanoMIRACL
        group_by: benchmark
