overalls:
  - name: Overall
    label: Overall
    benchmarks:
      - NanoMMTEB-v2
      - NanoRTEB
      - name: MNanoBEIR
        group_by: task_name
      - NanoBIRCO
      - NanoMLDR
      - NanoLongEmbed
      - NanoDAPFAM
      - NanoCoIR
      - NanoIFIR
      - NanoLaw
      - NanoMedical
      - NanoRARb
      - NanoBRIGHT
      - NanoCodeRAG
      - NanoChemTEB
      - NanoR2MED
      - NanoBuiltBench
      - NanoCMTEB
      - NanoIndicQA
      - NanoMuPLeR
      - NanoMTEB-v2
      - NanoMTEB-Dutch
      - NanoMTEB-French
      - NanoMTEB-German
      - NanoJMTEB-v2
      - NanoMTEB-Korean
      - NanoFaMTEB-v2
      - NanoMTEB-Polish
      - NanoRuMTEB
      - NanoMTEB-Scandinavian
      - NanoMTEB-Spanish
      - NanoMTEB-Thai
      - NanoVNMTEB
      - NanoMTEB-Misc
      - NanoMIRACL
  - name: Core
    label: Core
    benchmarks:
      - name: MNanoBEIR
        group_by: task_name
      - NanoMMTEB-v2
      - NanoRTEB
      - NanoMLDR
      - NanoBRIGHT
      - NanoCoIR
  - name: Core-EN
    label: Core-EN
    benchmarks:
      - NanoRTEB
      - NanoBRIGHT
      - NanoCoIR
      - NanoMTEB-v2
