name: NanoMedical
dataset_id: hakari-bench/NanoMedical
benchmark_kind: nano
corpus_config: corpus
queries_config: queries
qrels_config: qrels
candidate_config: bm25
splits:
  - NanoCUREv1
  - NanoNFCorpus
  - NanoTRECCOVID
  - NanoTRECCOVIDPL
  - NanoSciFact
  - NanoSciFactPL
  - NanoMedicalQA
  - NanoPublicHealthQA
  - NanoCmedqa
  - NanoCMedQAv2reranking
