name: MNanoBEIR
datasets:
  - NanoBEIR-en
  - name: NanoBEIR-ar
    dataset_id: hakari-bench/NanoBEIR-ar
    benchmark_kind: nanobeir
  - name: NanoBEIR-de
    dataset_id: hakari-bench/NanoBEIR-de
    benchmark_kind: nanobeir
  - name: NanoBEIR-es
    dataset_id: hakari-bench/NanoBEIR-es
    benchmark_kind: nanobeir
  - name: NanoBEIR-it
    dataset_id: hakari-bench/NanoBEIR-it
    benchmark_kind: nanobeir
  - name: NanoBEIR-fr
    dataset_id: hakari-bench/NanoBEIR-fr
    benchmark_kind: nanobeir
  - name: NanoBEIR-pt
    dataset_id: hakari-bench/NanoBEIR-pt
    benchmark_kind: nanobeir
  - name: NanoBEIR-no
    dataset_id: hakari-bench/NanoBEIR-no
    benchmark_kind: nanobeir
  - name: NanoBEIR-sv
    dataset_id: hakari-bench/NanoBEIR-sv
    benchmark_kind: nanobeir
  - name: NanoBEIR-sr
    dataset_id: hakari-bench/NanoBEIR-sr
    benchmark_kind: nanobeir
  - name: NanoBEIR-ko
    dataset_id: hakari-bench/NanoBEIR-ko
    benchmark_kind: nanobeir
  - name: NanoBEIR-ja
    dataset_id: hakari-bench/NanoBEIR-ja
    benchmark_kind: nanobeir
  - name: NanoBEIR-vi
    dataset_id: hakari-bench/NanoBEIR-vi
    benchmark_kind: nanobeir
  - name: NanoBEIR-th
    dataset_id: hakari-bench/NanoBEIR-th
    benchmark_kind: nanobeir
